// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzP4AUU7h3whHkJgLI2pvI2exh1Pb7Wgg',
    appId: '1:728109554859:android:f2df35341c81526d7febee',
    messagingSenderId: '728109554859',
    projectId: 'study-app-af9fb',
    databaseURL: 'https://study-app-af9fb-default-rtdb.firebaseio.com',
    storageBucket: 'study-app-af9fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemcEr_2VaEV6phtXxge86JqGcWjPeIY4',
    appId: '1:728109554859:ios:866aec9e964e379a7febee',
    messagingSenderId: '728109554859',
    projectId: 'study-app-af9fb',
    databaseURL: 'https://study-app-af9fb-default-rtdb.firebaseio.com',
    storageBucket: 'study-app-af9fb.firebasestorage.app',
    androidClientId: '728109554859-o1ef7cb8pmug2umvfvjmql3lsf5kek7a.apps.googleusercontent.com',
    iosClientId: '728109554859-8qhu85sfjs1upntrcjcrl6rcvkvb89ar.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );
}
